name: "Enforce Governance Git Action"
description: "This is the github action"
inputs:
  greeting-name:
    description: "Name Variable"
    required: true
    default: 'SKC'
outputs:
  time: # Id of the output
    description: 'This is the time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
  